spring:
  profiles:
    active: development
---
spring:
  profiles: development
  redis:
    host: 127.0.0.1
    port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/dev
    username: root
    password: parola86
    initialize: true
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
#spring:
#  profiles: docker
#  redis:
#    host: redis
#    port: 6379
#  datasource:
#    url: jdbc:mysql://mysql:3306/dev?useSSL=false
#    username: root
#    password: dbpass
#    initialize: true
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://discovery-service:8761/eureka/
---
#spring:
#  profiles: test
#  redis:
#    host: localhost
#    port: 6379
#  jpa:
#    database: H2
#  datasource:
#    initialize: false